name: cocoapods

on: 
  push:
    branches: 
      - master
      - hotfix
  pull_request:
    branches: 
      - '*'


jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install cocoapods
      run: gem install cocoapods
    - name: Run mac os x tests
      run: xcodebuild -project WebLinking.xcodeproj -scheme WebLinking test -destination "platform=macOS" | xcpretty && exit ${PIPESTATUS[0]}
    - name: Upload results
      run: bash <(curl -s https://codecov.io/bash)
    - name: Run ios tests
      run: xcodebuild -project WebLinking.xcodeproj -scheme WebLinking test -destination "name=iPhone 11 Pro" ONLY_ACTIVE_ARCH=NO | xcpretty && exit ${PIPESTATUS[0]}
    - name: Run pod lint
      run: pod lib lint --quick
